# print(2+3)
# print(3-1)
# print(6/2)
# print(6//2)
# print(2**3)
# # print(9%2)
# # print(2*3)
# print(2**3/3+6-4)
# # PEMDAS(parenthisis,exponent,multiplay,addition,subtraction) (work left to right M D & A S)
